# Generated by Django 5.2.7 on 2025-10-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
