# Generated by Django 5.2.7 on 2026-03-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
