# Generated by Django 5.2.7 on 2025-10-27 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_useraccount_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_approved',
        ),
    ]
