# Generated by Django 5.2.7 on 2026-04-02 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_useraccount_is_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('Out-Patient', 'Out-Patient'), ('In-Patient', 'In-Patient')], max_length=20)),
                ('bill_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('staying_days', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], default='Unpaid', max_length=15)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'Bills',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='BillItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospital.bills')),
            ],
            options={
                'db_table': 'Bill_Items',
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('cnic', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('is_approved', models.BooleanField(default=False)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.departments')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Doctors',
                'db_table': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors')),
            ],
            options={
                'db_table': 'DoctorSchedule',
            },
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=5)),
                ('patient_type', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD')], default='OPD', max_length=10)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='PatientFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patients')),
            ],
        ),
        migrations.CreateModel(
            name='InPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('bed_no', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
                ('admission_time', models.TimeField()),
                ('diagnosis', models.TextField()),
                ('is_discharged', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharge', 'Discharge'), ('Billed', 'Billed')], default='Admitted', max_length=20)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patients')),
            ],
            options={
                'verbose_name_plural': 'In-Patietns',
                'db_table': 'In-Patietns',
            },
        ),
        migrations.AddField(
            model_name='bills',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='hospital.patients'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=15)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('token', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Serving', 'Serving'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Billed', 'Billed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.departments')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors')),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patients')),
            ],
            options={
                'db_table': 'Appointments',
                'unique_together': {('doctor', 'appointment_date', 'token')},
            },
        ),
    ]
