# Generated by Django 5.2.7 on 2025-10-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_remove_useraccount_is_approved'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraccount',
            table='users',
        ),
    ]
