# Generated by Django 5.2.7 on 2026-03-04 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_useraccount_is_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('cnic', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('blood_group', models.CharField(max_length=5)),
                ('patient_type', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD')], default='OPD', max_length=10)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Patients',
                'db_table': 'Patients',
            },
        ),
    ]
