# Generated by Django 5.2.7 on 2026-04-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_bills_departments_billitems_doctors_doctorschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
