# Generated by Django 5.2.7 on 2026-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_useraccount_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
