# Generated by Django 5.2.7 on 2026-03-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_departments'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departments',
            table='Departments',
        ),
    ]
