# Generated by Django 5.2.7 on 2026-03-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_patientfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='InPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('bed_no', models.CharField(max_length=50)),
                ('admission_date', models.DateField()),
                ('admission_time', models.TimeField()),
                ('diagnosis', models.TextField()),
                ('is_discharged', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patients')),
            ],
            options={
                'verbose_name_plural': 'In-Patietns',
                'db_table': 'In-Patietns',
            },
        ),
    ]
