# Generated by Django 5.2.7 on 2026-06-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_first_login',
            field=models.BooleanField(default=False),
        ),
    ]
